name: Direct dowloand data v0

on:
  # push:
  #   branches:
  #     - main
  #     - master
  workflow_dispatch:
  schedule:
    - cron: '01,21,41 6-21 * * *'
    - cron: '01 22,00,02,04 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download data
        run: |
          curl -x ${{ secrets.PROXY_SERVERS }} 'https://api.nike.sk/api/nikeone/v1/boxes/extended/sport-event-id?sportEventId=42866077' > v0/source/data_42866077.json
       
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date +%FT%T%z)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push 

